### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by Rajarshi07** [alesaudate/camel-drools-webservices#1]
Hey man, do you have some documentation for this one?

**Comment by alesaudate** [comment]
Hey,

No, I don't. Do you need something specific ?

Em qui., 24 de ago. de 2023 20:11, Rajarshi Ghosh Dastidar <
***@***.***> escreveu:

**Comment by Rajarshi07** [comment]
yes... this looks like something i can use as a starting point to learn camel and drools integration. Can you please give me a quickstart guide, or just the  prerequisites ,setup, and commands required to run the project.

Thank you

**Comment by alesaudate** [comment]
But this project is 12 years old. There's an extremely high chance that
things have changed nowadays. So it has value only for me, now, as I have
the means to show that I have been working with Camel for more than 12
years now, but that's all.

Em qui., 24 de ago. de 2023 20:47, Rajarshi Ghosh Dastidar <
***@***.***> escreveu:

**Comment by Rajarshi07** [comment]
I'm sorry I didn't notice the commit date. Just starting to learn camel and drools and came by your repo.

Thank you so much for the quick response and for helping me out. Have a great day.
